# Generated by Django 2.2.27 on 2022-03-10 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_post_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タイトル')),
                ('profile', models.CharField(max_length=50, verbose_name='profile')),
                ('Twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('Qiita', models.CharField(max_length=100, verbose_name='キータ ')),
                ('Link', models.CharField(max_length=100, verbose_name='link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
