# Generated by Django 2.2.27 on 2022-03-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
